[book]
authors = ["ZoomQuiet"]
language = "en"
multilingual = false
src = "src"
title = "be Rustaceans"
base_url = "rust.101.so"

# Enables the `mdbook-template` preprocessor
#[preprocessor.template]

[build]
build-dir = "docs"
